### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error

### ISSUE THREAD

**Issue by rafish1** [jsimpso/PyFortiAPI#17]
Hi,

I'm trying to login to Fortigate 3600D version 5.6.12 with pyfortiapi,

**this is my script:**
import pyfortiapi

device = pyfortiapi.FortiGate(ipaddr="10.68.10.120",
                                  username="flowcapture",
                                  password="pfjwHp1wfdrse3jdgtykjkjves")  # This is the API key i created in the Fortigate

addresses = device.get_firewall_address()
print(addresses)

my error are:
Traceback (most recent call last):
  File "ps-aux.py", line 17, in <module>
    nodlist = device.get_firewall_address()
  File "/usr/local/lib/python3.6/site-packages/pyfortiapi.py", line 158, in get_firewall_address
    results = self.get(api_url)
  File "/usr/local/lib/python3.6/site-packages/pyfortiapi.py", line 94, in get
    session = self.login()
  File "/usr/local/lib/python3.6/site-packages/pyfortiapi.py", line 53, in login
    login_check.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required for url: https://10.68.10.120:443/api/v2/cmdb/system/vdom

I checked the credentials and the user and password are ok
curl -ki -H "Content-Type: application/json" -X POST https://10.68.10.120/logincheck?username=xxxx&secretkey=xxxxx 
The result is
HTTP/1.1 200 OK
Date: Tue, 12 Jan 2021 14:01:25 GMT
Server: xxxxxxxx-xxxxx
Set-Cookie: APSCOOKIE_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: VDOM_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: CENTRAL_MGMT_OVERRIDE_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: EDIT_HISTORY_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: FILE_DOWNLOADING_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: csrftoken_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: ccsrftoken_17029277275916847658="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict
Set-Cookie: ccsrftoken="0%260"; path=/; expires=Mon, 25-Jan-1971 14:01:25 GMT; secure; SameSite=Strict

Any help will be appreciated

**Comment by jsimpso** [comment]
Hi @rafish1 

I don't currently have access to a FortiGate to do any testing, but will try to organise access to a virtual unit to assist with troubleshooting.

**Comment by rafish1** [comment]
OK,
Thanks
I also checked it with rest api 
the script i wrote:
import requests
#import json,urllib3,requests

#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

response = requests.get('https://10.68.10.120/api/v2/cmdb/firewall/address/?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g')
#print(response)

And I received different error 
Traceback (most recent call last):
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/python-environments/python_env/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='132.68.234.120', port=443): Max retries exceeded with url: /api/v2/cmdb/firewall/address/?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fortilogin.py", line 8, in <module>
    response = requests.get('https://10.68.10.120/api/v2/cmdb/firewall/address/?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g')
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.68.234.10', port=443): Max retries exceeded with url: /api/v2/cmdb/firewall/address/?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),) 

Any Ideas ?

**Comment by corvese** [comment]
@ratfish, try setting a value of False to the verify argument in your https request. I just tested on my firewall and this works. Python is checking to see if the certificate is valid, but it is self-signed and likely failing because of this.

```
import requests

url = "https://192.168.1.1/api/v2/cmdb/firewall/address?access_token=3894eugva4ith3t4yga9485yhaf44"

response = requests.request("GET", url, verify=False)

print(response.text)
```

**Comment by rafish1** [comment]
Thank you very much the ssl problem solved,
By default the login is to vdom root but I'm trying to login to vdom Dos (Api key has access to this vdom), 

See configuration from Fortigate (global)
edit "flowcapture"
        set api-key ENC SH2jfhnqK3i9kKKZwsvEV43IZScCapfl4rqsMdZ5EvK6gudZhg1lAXe5qBHJoE=
        set accprofile "REST API admin"
        set vdom "**Dos**" "root"
        config trusthost


#!/usr/bin/python3.6

import requests
import os
import json,urllib3,requests
import urllib.request
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

#with urllib.request.urlopen("https://132.68.234.120/", context=ssl.SSLContext()) as url:
#print(url.read())

#url = "https://10.68.234.10/api/v2/cmdb/firewall/address?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g" #this url works fine
url = "https://10.68.234.10/api/v2/cmdb/firewall/address/?vdom=Dos?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g"
response = requests.request("GET", url, verify=False)

print(response.text)

According to Fortigate API the syntax should be:
GET /api/v2/cmdb/firewall/address/?vdom=vdom1

The error I get is :
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>401 Authorization Required</TITLE>
</HEAD><BODY>
Authorization Required
This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.<P>
<P>Additionally, a 401 Authorization Required
error was encountered while trying to use an ErrorDocument to handle the request.
</BODY></HTML>


Any Idea ?

**Comment by dix0nym** [comment]
`url = "https://10.68.234.10/api/v2/cmdb/firewall/address/?vdom=Dos?access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g"`

@ratfish is that a typo?

correct would be following url:

`url = "https://10.68.234.10/api/v2/cmdb/firewall/address/?vdom=Dos&access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g"`

the first GET-parameter is defined by `?<name>=<value>`, following parameters need `&<name>=<value>`

But that is your own script? What is the error regarding the PyFortiAPI?

**Comment by rafish1** [comment]
Hi,

Yes, sorry it was typo, this link url = "https://10.68.234.10/api/v2/cmdb/firewall/address/?vdom=Dos&access_token=y9wQrbGGxQGGgkzsswsQ4nypfH7y9g"
Is working with chrome only not even from chrome incognito, I'm very confused .......
I tried to do it with rest API but maybe the PyFortiAPI is better to achieve my goal

I'm very new with python, API, sorry if I'm bothering you 
About PyFortiAPI, this is the script: (**from: https://pyfortiapi.readthedocs.io/en/latest/user/operations.html#)**
 
import pyfortiapi
device = pyfortiapi.FortiGate(ipaddr="10.68.234.10",
                              username="flowcapture",
                              vdom="Dos",
                              password="y9wQrbGGxQGGgkzsswsQ4nypfH7y9g")

addresses = device.get_firewall_address()
print(addresses)


This is the error:
Traceback (most recent call last):
  File "pifortoapi.py", line 9, in <module>
    addresses = device.get_firewall_address()
  File "/root/python-environments/python_env/lib/python3.6/site-packages/pyfortiapi.py", line 158, in get_firewall_address
    results = self.get(api_url)
  File "/root/python-environments/python_env/lib/python3.6/site-packages/pyfortiapi.py", line 94, in get
    session = self.login()
  File "/root/python-environments/python_env/lib/python3.6/site-packages/pyfortiapi.py", line 53, in login
    login_check.raise_for_status()
  File "/root/python-environments/python_env/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Authorization Required for url: https://10.68.234.10:443/api/v2/cmdb/system/vdom

My goal is be able to add and delete address from group,
I enabled flow-capture that gets netflow from my router and I want that the script will check incoming ip's and if src ip passed flow threshold the script shoul create address and attached him to group address 

If you can help with the PyFortiAPI error it will be great 
 
Thank you very much with your assist

**Comment by jsimpso** [comment]
Hi @rafish1 Still struggling to get hold of a virtual unit at the moment sadly.

Given that the error being thrown there is a 401, have you verified manually that the given user has access to the resource?

**Comment by HardipinderS** [comment]
@rafish1 this is credentials related issue. I had faced the same. I would request you to create the credentials using CLI and add api authorization to the policies. I hope this helps. The sdk is correct and has no issues. 

I think the best that can be done is adding a condition if the response is 400 range , we can print the same

**Comment by thecraigus** [comment]
> @rafish1 this is credentials related issue. I had faced the same. I would request you to create the credentials using CLI and add api authorization to the policies. I hope this helps. The sdk is correct and has no issues.
> 
> I think the best that can be done is adding a condition if the response is 400 range , we can print the same

Hi, 

Please can you help me - I am running into the 401 issue. 

How can I overcome it?

**Comment by HardipinderS** [comment]
> > @rafish1 this is credentials related issue. I had faced the same. I would request you to create the credentials using CLI and add api authorization to the policies. I hope this helps. The sdk is correct and has no issues.
> > I think the best that can be done is adding a condition if the response is 400 range , we can print the same
> 
> Hi,
> 
> Please can you help me - I am running into the 401 issue.
> 
> How can I overcome it?

401 means you're stuck with authorization issue. 

Just to make sure where you're getting stuck, try opening this link https://{ipaddr}:{port}/logincheck, using requests or in browser. If you get 200 means you have basic access to the API. Incase you get 401 there too that means that the API creds were not properly created. 

If logincheck gives 401, then try creating new credentials from cli with access over all the API endpoints, with specific access(if need to get data read-only will suffice, if post then go admin). If the latter is correct, then edit the credentials in the cli, and provide the endpoint access. 

Hope this helps
